### ISSUE TITLE
readme - explain how hibernate can be used with vertx

### ISSUE THREAD

**Issue by ORESoftware** [aesteve/vertx-hibernate#3]
I am trying to figure out if I can use an ORM with Vertx. I wrote some server with Golang, but Golang kinda sucks and doesn't have a good ORM lib for traditional relational dbs...anyway so trying this with Java but looking for a good ORM to pair with Vertx.

**Comment by aesteve** [comment]
Hello.

This project was just an experiment I did a few years ago just to figure out how we could use Vert.x together with a traditional ORM system.

Long story short : it's not really possible.

In fact, the main issue with "traditional" ORMs like JPA implementation and Hibernate, is laziness.
Imagine you have a table `PERSON` mapped onto a `Person` class, and a `DOG` table mapped onto a `Dog`  class.

You'll probably end-up with such a mapping:
```
class Person {
  @OneToMany
  Set<Dog> getCompanions() {...}
}
```

By default, Hibernate (and I guess other JPA implementations, too) are lazy. Which means if you extract a person from the database by its name or id, the "companions" set will be empty. In fact, it's not a real Set, it's a proxy collection.
The first time you'll access an item in this collection, Hibernate will issue a query to the DB to fetch dogs.
And this is where we're screwed.

In a non-blocking-io world, every query is executed asynchronously. Which means, your companions are no longer a `Set<Dog>`, but more something like a `CompletableFuture<Set<Dog>>`.

One solution would be to "eager-fetch" every property. But then, what would be the point of using an ORM ?

Some stuff you might be interested in : 
* not using an ORM, but something like JOOQ instead
* maybe watch what GORM 5.0 (which introduced the notion of an async ORM) did
* take a look at how micronaut deals with JPA in an async manner (I still havent taken the time tofigure out how they're doing it)

**Comment by ORESoftware** [comment]
Hmmm, I can't figure out what you are saying. Are you saying that Hibernate sucks, or that Hibernate is not very compatible with Vertx?

I was following the instructions here:
https://github.com/vert-x3/vertx-examples/tree/master/spring-examples/spring-example

So I have 2 verticles, one is the server, one is a spring thing, and in the spring verticle I have:

```java
  private Handler<Message<String>> allProductsHandler(UserService service) {
    // It is important to use an executeBlocking construct here
    // as the service calls are blocking (dealing with a database)
    return msg -> pool.<String>executeBlocking(f -> {
        try {
          f.complete(mapper.writeValueAsString(service.getAllUsers()));
        } catch (JsonProcessingException e) {
          System.out.println("Failed to serialize result");
          f.fail(e);
        }
      },
      result -> {
        if (result.succeeded()) {
          msg.reply(result.result());
        } else {
          msg.reply(result.cause().toString());
        }
      });
  }
```

the spring verticle sends the data to the server verticle.

**Comment by aesteve** [comment]
Please don't put words in my mouth.

I'm just saying that adapting an ORM to an "asynchronous" world is not an easy task at all. I tried to (in this project), and didn't succeed.
Some people seem to have succeeded to do so (see the pointers I gave you in my previous answer). But I did not, and was stuck because of the lazy nature of ORMs in general.

Anyway, this project was an experiment I did a long time ago, I rally DO NOT RECOMMEND at all using it in production.

If you have any question please ask it in the Vert.x Google Group instead.

**Comment by ORESoftware** [comment]
Hey thanks nah I wasn't trying to get your goat, was simply trying to wrestle as much info out of you as possible :)

I agree the Spring sync + Vertx world is a little wonky, but maybe it will work, most likely if it does work I won't stray too far from the techniques in the liink above.

**Comment by aesteve** [comment]
If you need async to achieve a very high level of scalability, probably using `executeBlocking` everywhere isn't really a good starting point.

Using an internal thread pool is probably going to end up killing scalability.

Turning to https://github.com/reactiverse/reactive-pg-client with JOOQ for instance may be really really interesting. Full async, full NIO, you'll have a very very high throughput.

If you don't want to achieve a very high level of scalability, then the traditional ORM-blocking approach is gonna be OK.

**Comment by aesteve** [comment]
And again, I highly recommend you using discussion channels like Google Groups, gitter, slack or whatever in order to **ask questions** not opening a lot of issues in a lot of different repositories.

Issues should be kept for bugs, really, not for informal discussions.

You're asking a question about Vert.x and ORMs. Please ask it (after doing some search in the Google Group, I guess a lot of this has already been answered) in the vert.x google discussion group. You'll receive many more comments.

Also, please kindly note that using an open source project issue to "wrestle as much info out of you as possible" is not really cool.

Stackoverflow is also a good place to ask your question about "Vert.x and ORMs".

**Comment by ORESoftware** [comment]
@aesteve turn that frown upside down! 🇫🇷 🇧🇪  🇫🇷 🇧🇪  🇫🇷
